package edu.amrita.amritacafe.menu

val defaultMenu : List<MenuItem> = listOf(
    MenuItem("Bread", "BREAD", 3, Availability.All, Location.Sides, Category.Side),
    MenuItem("Butter", "BUTT", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Capsicum", "CAP", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Carrot", "CARROT", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Honey", "HON", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Jam", "JAM", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Sliced Cheese", "SL CH", 20, Availability.All, Location.Sides, Category.Side),
    MenuItem("Mustard", "MRD", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Choco Spread", "CHOC", 15, Availability.All, Location.Sides, Category.Side),
    MenuItem("Peanut Butter", "PB", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Patty", "PATTY", 20, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Cucumber", "CUKE", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Pesto", "PSTO", 25, Availability.All, Location.Sides, Category.Side),
    MenuItem("Raw Egg", "RAW EGG", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Gomasio", "GOMAZ", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Ketchup", "KETUP", 5, Availability.All, Location.Sides, Category.Side),
    MenuItem("Olive", "OLV", 30, Availability.All, Location.Sides, Category.Side),
    MenuItem("Onion", "ON", 5, Availability.All, Location.Sides, Category.Side),
    MenuItem("Pickle", "PKL", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Dressing", "DRS", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Soya", "SOYA", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Sprouts", "SPRTS", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Fresh Tomato", "FRT", 5, Availability.All, Location.Sides, Category.Side),
    MenuItem("Tomato Sauce", "TOM", 10, Availability.All, Location.Sides, Category.Side),
    MenuItem("Bun", "BUN", 10, Availability.LunchDinner, Location.Sides, Category.Side),
    MenuItem("Grated Cheese", "CH", 20, Availability.All, Location.Sides, Category.Side),
    MenuItem("Mayo", "MAYO", 10, Availability.LunchDinner, Location.Sides, Category.Side),

    MenuItem("Sm Fries", "SMFF", 30, Availability.LunchDinner, Location.Fries, Category.Fries),
    MenuItem("Lg Fries", "LGFF", 60, Availability.LunchDinner, Location.Fries, Category.Fries),
    MenuItem("Sm Fries Salt", "SMSAFF", 35, Availability.LunchDinner, Location.Fries, Category.Fries),
    MenuItem("Lg Fries Salt", "LGSAFF", 70, Availability.LunchDinner, Location.Fries, Category.Fries),

    MenuItem("Grilled Cheese", "GC", 40, Availability.All, Location.Grill, Category.Sandwich),
    MenuItem("Egg Cheese Sand", "ECS", 60, Availability.All, Location.Grill, Category.Sandwich),
    MenuItem("Omelet Sandwich", "OMS", 50, Availability.All, Location.Grill, Category.Sandwich),
    MenuItem("Deluxe Grill CH", "DXL GC", 75, Availability.LunchDinner, Location.Grill, Category.Sandwich),
    MenuItem("Grilled Ch FRT", "GC FRT", 45, Availability.LunchDinner, Location.Grill, Category.Sandwich),

    MenuItem("Simple Salad", "SAL", 30, Availability.LunchDinner, Location.Salad, Category.Salad),
    MenuItem("Sprout Salad", "SPRSAL", 50, Availability.LunchDinner, Location.Salad, Category.Salad),
    MenuItem("Deluxe Salad", "DXL SAL", 90, Availability.LunchDinner, Location.Salad, Category.Salad),
    MenuItem("Pesto Salad", "PSTO SAL", 80, Availability.LunchDinner, Location.Salad, Category.Salad),
    MenuItem("Quinoa Salad", "QNA SAL", 150, Availability.LunchDinner, Location.Salad, Category.Salad),

    MenuItem("French Toast", "FT", 40, Availability.Breakfast, Location.Grill, Category.Breakfast),
    MenuItem("Ragi Pancake", "RAG PAN", 40, Availability.Breakfast, Location.Grill, Category.Breakfast),
    MenuItem("Pancake", "PAN", 40, Availability.Breakfast, Location.Grill, Category.Breakfast),
    MenuItem("Hash Brown", "HASH", 20, Availability.Breakfast, Location.Grill, Category.Breakfast),
    MenuItem("Oatmeal", "OAT", 30, Availability.Breakfast, Location.Kitcheri, Category.Breakfast),
    MenuItem("Ragi Porridge", "POR", 30, Availability.Breakfast, Location.Kitcheri, Category.Breakfast),
    MenuItem("Vegan Omelet", "VN OM", 40, Availability.Breakfast, Location.Grill, Category.Breakfast),

    MenuItem("Cheese Pizza", "CH PZA", 100, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Olive Pizza", "OLV PZA", 135, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Veg Pizza", "VEG PZA", 125, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Vegan Veg Pizza", "VN VEG PZA", 100, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Gourmet Pizza", "GM PZA", 150, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Vegan Gourmet PZA", "VN GM PZA", 125, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Pesto Pizza", "PSTO PZA", 125, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Paneer Pizza", "PAN PZA", 150, Availability.LunchDinner, Location.Pizza, Category.Pizza),
    MenuItem("Mediter. Pizza", "MED PZA", 125, Availability.LunchDinner, Location.Pizza, Category.Pizza),

    MenuItem("Veggie Burger", "VB", 40, Availability.LunchDinner, Location.Grill, Category.Burger),
    MenuItem("Cheese Burger", "CB", 60, Availability.LunchDinner, Location.Grill, Category.Burger),
    MenuItem("Patty", "PATTY", 20, Availability.LunchDinner, Location.Grill, Category.Burger),
    MenuItem("Deluxe Burger", "DLXB", 80, Availability.LunchDinner, Location.Grill, Category.Burger),
    // Check price.
    MenuItem("Pesto Burger", "PSTOB", 65, Availability.LunchDinner, Location.Grill, Category.Burger),

    MenuItem("Toast", "T", 3, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Butter Jam Toast", "BJT", 15, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Butter Toast", "BT", 10, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Jam Toast", "JT", 10, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Peanut But Toast", "PBT", 10, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Cheese Toast", "CHT", 25, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Honey Toast", "HT", 10, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Butter Honey Toast", "BHT", 20, Availability.All, Location.Grill, Category.Toast),
    MenuItem("Choco Toast", "CHOC T", 15, Availability.All, Location.Grill, Category.Toast),

    MenuItem("Kitcheri", "KITCH", 30, Availability.LunchDinner, Location.Kitcheri, Category.Kitcheri),
    MenuItem("Steamed Veg", "ST VEG", 30, Availability.LunchDinner, Location.Kitcheri, Category.Kitcheri),
    MenuItem("Quinoa", "QNA", 100, Availability.LunchDinner, Location.Kitcheri, Category.Kitcheri),
    MenuItem("Steamed Broccoli", "ST BROC", 100, Availability.LunchDinner, Location.Kitcheri, Category.Kitcheri),
    MenuItem("Hummus", "HUM", 30, Availability.LunchDinner, Location.Kitcheri, Category.Kitcheri),

    MenuItem("Jam", "JAM", 10, Availability.Breakfast, Location.Sides, Category.Topping),
    MenuItem("Peanut Butter", "PB", 10, Availability.Breakfast, Location.Sides, Category.Topping),
    MenuItem("Butter", "BUTT", 10, Availability.Breakfast, Location.Sides, Category.Topping),
    MenuItem("Honey", "HON", 10, Availability.Breakfast, Location.Sides, Category.Topping),
    MenuItem("Choco Spread", "CHOC", 15, Availability.Breakfast, Location.Sides, Category.Topping),

    MenuItem("Plain Pasta", "PL PSTA", 30, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),
    MenuItem("Pasta Tomato Sauce", "PSTA TOM", 60, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),
    MenuItem("Pasta Tomato Cheese", "PAST TOM CH", 80, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),
    MenuItem("Pasta All Soy", "PAST ALL SOY", 90, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),
    MenuItem("Pesto Pasta", "PSTO PAST", 60, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),
    MenuItem("Vegan Gourmet Pasta", "VN GM PAST", 100, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),
    MenuItem("Deluxe Pasta", "DLX PAST", 115, Availability.LunchDinner, Location.Kitcheri, Category.Pasta),

    MenuItem("Egg Sunny Side Up", "FE SSU", 20, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Fried Egg Overhard", "FE OH", 20, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Plain Omelet", "OM", 40, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Veggie Omelet", "VEG OM", 60, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Deluxe Omelet", "DXL OM", 115, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Cheese Omelet", "OM CH", 60, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Fresh Tomato Omelet", "OM FRT", 45, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Pesto Omelet", "PSTO OM", 70, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Olive Omelet", "OLV OM", 75, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Veggie Cheese Omelet", "VEG CH OM", 80, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Gourmet Omelet", "GM OM", 110, Availability.All, Location.Grill, Category.Eggs),
    MenuItem("Onion Omelet", "ON OM", 45, Availability.All, Location.Grill, Category.Eggs)
)