package edu.amrita.amritacafe.menu

//val defaultUsMenu = listOf(MenuItem())

fun destroyMenuString(){

}

val menuString = """Granola,3,Gran,0.5Breakfast),
MenuItem(Chia,3,Chia,0.5Breakfast),
MenuItem(Bagels,3,Bag,0.5Breakfast),
MenuItem(chream cheese,1,cheese,0.5Breakfast),
MenuItem(Breakfast Sandwich,4,Br Sand,0.5Breakfast),
MenuItem(Samosa,1,5,Sam,1Indian Snacks),
MenuItem(Eggplant Bhaji,1,5,Eg Bhaj,1Indian Snacks),
MenuItem(Aloo Tikki,1,5,Tikki,1Indian Snacks),
MenuItem(Bonda,1,5,Bonda,1Indian Snacks),
MenuItem(Parippu Vada,1,5,Parip,1Indian Snacks),
MenuItem(Methu Vada,1,5,Methu,1Indian Snacks),
MenuItem(Cauliflower,1,5,Ca Bhaj,1Indian Snacks),
MenuItem(Idli,1,25,Idli,2Curry Corner),
MenuItem(Sambar,2,Sam,2Curry Corner),
MenuItem(Puri,1,5,Puri,2Curry Corner),
MenuItem(Chole,2,Chole,2Curry Corner),
MenuItem(Panner Curry,3,5,Pa Curry,2Curry Corner),
MenuItem(Appam Curry,3,5,Ap Curry,2Curry Corner),
MenuItem(Appam,2,Appam,2Curry Corner),
MenuItem(Masala Dosa,7,Ma Dosa,3Dosa & more),
MenuItem(Plain Dosa,6,Dosa,3Dosa & more),
MenuItem(Quiona Upma,2,Upuma,3Dosa & more),
MenuItem(Chaat,5,Chaat,3Dosa & more),
MenuItem(Poha,2,Poha,3Dosa & more),
MenuItem(Uttapam,5,Uttap,3Dosa & more),
MenuItem(Bhutura,5,,3Dosa & more),
MenuItem(Cheese Pizza,3,Ch Piz,4Pizza & More),
MenuItem(Vegetarian Pizza,3,5,Veg Piz,4Pizza & More),
MenuItem(Panini 1,5,Pan,4Pizza & More),
MenuItem(Bom Panini,5,Bom Pan,4Pizza & More),
MenuItem(Veggie Puff,3,Puff,4Pizza & More),
MenuItem(Fries,3,Fries,4Pizza & More),
MenuItem(Raw Pie,7,Raw Pi,5Raw),
MenuItem(Raw Bar,5,Raw Bar,5Raw),
MenuItem(Springroll,5,Spring,5Raw),
MenuItem(Large cake,4,lg Cake,6Sweets homemade),
MenuItem(Cake,3,5,cake,6Sweets homemade),
MenuItem(Bars,3,Bars,6Sweets homemade),
MenuItem(Cookies,2,Cookie,6Sweets homemade),
MenuItem(Energy Balls,1, E balls,6Sweets homemade),
MenuItem(Pie,4,Pie,6Sweets homemade),
MenuItem(Whipped cream,3,5,Cream,6Sweets homemade),
MenuItem(Breakfast scones,3,5,Scones,6Sweets homemade),
MenuItem(Chai,2,5,Chai,7Hot Drinks),
MenuItem(Veg Chai,3,5,Chai,7Hot Drinks),
MenuItem(Espresso,2,Esp,7Hot Drinks),
MenuItem(Americano,3,Amer,7Hot Drinks),
MenuItem(Cappuchino,3,5,Cap,7Hot Drinks),
MenuItem(Latte,5,Lat,7Hot Drinks),
MenuItem(Madras Coffe,3,5,Ma Cof,7Hot Drinks),
MenuItem(Filter Coffee,3,Reg Cof,7Hot Drinks),
MenuItem(Herbal Tea,2,5, Herb T,7Hot Drinks),
MenuItem(Mocha,5,Moch,7Hot Drinks),
MenuItem(Lassi,2,5,Lassi,8Juice & smoothie),
MenuItem(Orange Juice,4,O Jui,8Juice & smoothie),
MenuItem(green Juice,5,G Jui,8Juice & smoothie),
MenuItem(Red juice,5,R Jui,8Juice & smoothie),
MenuItem(Yellow smoothie,6,Y Smo,8Juice & smoothie),
MenuItem(Red smoothis,6,R Smo,8Juice & smoothie),
MenuItem(Green smoothis,6,Gr Smo,8Juice & smoothie),
MenuItem(Tumeric shot,3,Tu shot,8Juice & smoothie),
MenuItem(wheet grass shot,4,Wh shot,8Juice & smoothie),
MenuItem(Martinelli Apple juice, Izze, san pellegrino,2,5,Col Dri,9.1Cold Drinks),
MenuItem(Yerba Mate,4,5,Mate,9.1Cold Drinks),
MenuItem(Juice Box,1,J Box,9.1Cold Drinks),
MenuItem(Chips,1,Chips,9.2Cash register shelf
MenuItem(Chocolate,2,Choco,9.2Cash register shelf))"""


val defaultMenu : List<MenuItem> = listOf(
    MenuItem("Bread", "BREAD", 3, Availability.All, Category.Side),
    MenuItem("Butter", "BUTT", 10, Availability.All, Category.Side),
    MenuItem("Capsicum", "CAP", 10, Availability.All, Category.Side),
    MenuItem("Carrot", "CARROT", 10, Availability.All, Category.Side),
    MenuItem("Honey", "HON", 10, Availability.All, Category.Side),
    MenuItem("Jam", "JAM", 10, Availability.All, Category.Side),
    MenuItem("Sliced Cheese", "SL CH", 20, Availability.All, Category.Side),
    MenuItem("Mustard", "MRD", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Choco Spread", "CHOC", 15, Availability.All, Category.Side),
    MenuItem("Peanut Butter", "PB", 10, Availability.All, Category.Side),
    MenuItem("Patty", "PATTY", 20, Availability.LunchDinner, Category.Side),
    MenuItem("Cucumber", "CUKE", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Pesto", "PSTO", 25, Availability.All, Category.Side),
    MenuItem("Raw Egg", "RAW EGG", 10, Availability.All, Category.Side),
    MenuItem("Gomasio", "GOMAZ", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Ketchup", "KETUP", 5, Availability.All, Category.Side),
    MenuItem("Olive", "OLV", 30, Availability.All, Category.Side),
    MenuItem("Onion", "ON", 5, Availability.All, Category.Side),
    MenuItem("Pickle", "PKL", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Dressing", "DRS", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Soya", "SOYA", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Sprouts", "SPRTS", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Fresh Tomato", "FRT", 5, Availability.All, Category.Side),
    MenuItem("Tomato Sauce", "TOM", 10, Availability.All, Category.Side),
    MenuItem("Bun", "BUN", 10, Availability.LunchDinner, Category.Side),
    MenuItem("Grated Cheese", "CH", 20, Availability.All, Category.Side),
    MenuItem("Mayo", "MAYO", 10, Availability.LunchDinner, Category.Side),

    MenuItem("Sm Fries", "SMFF", 30, Availability.LunchDinner, Category.Fries),
    MenuItem("Lg Fries", "LGFF", 60, Availability.LunchDinner, Category.Fries),
    MenuItem("Sm Fries Salt", "SMSAFF", 35, Availability.LunchDinner, Category.Fries),
    MenuItem("Lg Fries Salt", "LGSAFF", 70, Availability.LunchDinner, Category.Fries),

    MenuItem("Grilled Cheese", "GC", 40, Availability.All, Category.Sandwich),
    MenuItem("Egg Cheese Sand", "ECS", 60, Availability.All, Category.Sandwich),
    MenuItem("Omelet Sandwich", "OMS", 50, Availability.All, Category.Sandwich),
    MenuItem("Deluxe Grill CH", "DXL GC", 75, Availability.LunchDinner, Category.Sandwich),
    MenuItem("Grilled Ch FRT", "GC FRT", 45, Availability.LunchDinner, Category.Sandwich),

    MenuItem("Simple Salad", "SAL", 30, Availability.LunchDinner, Category.Salad),
    MenuItem("Sprout Salad", "SPRSAL", 50, Availability.LunchDinner, Category.Salad),
    MenuItem("Deluxe Salad", "DXL SAL", 90, Availability.LunchDinner, Category.Salad),
    MenuItem("Pesto Salad", "PSTO SAL", 80, Availability.LunchDinner, Category.Salad),
    MenuItem("Quinoa Salad", "QNA SAL", 150, Availability.LunchDinner, Category.Salad),

    MenuItem("French Toast", "FT", 40, Availability.Breakfast, Category.Breakfast),
    MenuItem("Ragi Pancake", "RAG PAN", 40, Availability.Breakfast, Category.Breakfast),
    MenuItem("Pancake", "PAN", 40, Availability.Breakfast, Category.Breakfast),
    MenuItem("Hash Brown", "HASH", 20, Availability.Breakfast, Category.Breakfast),
    MenuItem("Oatmeal", "OAT", 30, Availability.Breakfast, Category.Breakfast),
    MenuItem("Ragi Porridge", "POR", 30, Availability.Breakfast, Category.Breakfast),
    MenuItem("Vegan Omelet", "VN OM", 40, Availability.Breakfast, Category.Breakfast),

    MenuItem("Cheese Pizza", "CH PZA", 100, Availability.LunchDinner, Category.Pizza),
    MenuItem("Olive Pizza", "OLV PZA", 135, Availability.LunchDinner, Category.Pizza),
    MenuItem("Veg Pizza", "VEG PZA", 125, Availability.LunchDinner, Category.Pizza),
    MenuItem("Vegan Veg Pizza", "VN VEG PZA", 100, Availability.LunchDinner, Category.Pizza),
    MenuItem("Gourmet Pizza", "GM PZA", 150, Availability.LunchDinner, Category.Pizza),
    MenuItem("Vegan Gourmet PZA", "VN GM PZA", 125, Availability.LunchDinner, Category.Pizza),
    MenuItem("Pesto Pizza", "PSTO PZA", 125, Availability.LunchDinner, Category.Pizza),
    MenuItem("Paneer Pizza", "PAN PZA", 150, Availability.LunchDinner, Category.Pizza),
    MenuItem("Mediter. Pizza", "MED PZA", 125, Availability.LunchDinner, Category.Pizza),

    MenuItem("Veggie Burger", "VB", 40, Availability.LunchDinner, Category.Burger),
    MenuItem("Cheese Burger", "CB", 60, Availability.LunchDinner, Category.Burger),
    MenuItem("Patty", "PATTY", 20, Availability.LunchDinner, Category.Burger),
    MenuItem("Deluxe Burger", "DLXB", 80, Availability.LunchDinner, Category.Burger),
    MenuItem("Pesto Burger", "PSTOB", 65, Availability.LunchDinner, Category.Burger),

    MenuItem("Toast", "T", 3, Availability.All, Category.Toast),
    MenuItem("Butter Jam Toast", "BJT", 15, Availability.All, Category.Toast),
    MenuItem("Butter Toast", "BT", 10, Availability.All, Category.Toast),
    MenuItem("Jam Toast", "JT", 10, Availability.All, Category.Toast),
    MenuItem("Peanut But Toast", "PBT", 10, Availability.All, Category.Toast),
    MenuItem("Cheese Toast", "CHT", 25, Availability.All, Category.Toast),
    MenuItem("Honey Toast", "HT", 10, Availability.All, Category.Toast),
    MenuItem("Butter Honey Toast", "BHT", 20, Availability.All, Category.Toast),
    MenuItem("Choco Toast", "CHOC T", 15, Availability.All, Category.Toast),

    MenuItem("Kitcheri", "KITCH", 30, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Steamed Veg", "ST VEG", 30, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Quinoa", "QNA", 100, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Steamed Broccoli", "ST BROC", 100, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Hummus", "HUM", 30, Availability.LunchDinner, Category.Kitcheri),

    MenuItem("Jam", "JAM", 10, Availability.Breakfast, Category.Topping),
    MenuItem("Peanut Butter", "PB", 10, Availability.Breakfast, Category.Topping),
    MenuItem("Butter", "BUTT", 10, Availability.Breakfast, Category.Topping),
    MenuItem("Honey", "HON", 10, Availability.Breakfast, Category.Topping),
    MenuItem("Choco Spread", "CHOC", 15, Availability.Breakfast, Category.Topping),

    MenuItem("Plain Pasta", "PL PSTA", 30, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pasta Tomato Sauce", "PSTA TOM", 60, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pasta Tomato Cheese", "PAST TOM CH", 80, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pasta All Soy", "PAST ALL SOY", 90, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pesto Pasta", "PSTO PAST", 60, Availability.LunchDinner, Category.Pasta),
    MenuItem("Vegan Gourmet Pasta", "VN GM PAST", 100, Availability.LunchDinner, Category.Pasta),
    MenuItem("Deluxe Pasta", "DLX PAST", 115, Availability.LunchDinner, Category.Pasta),

    MenuItem("Egg Sunny Side Up", "FE SSU", 20, Availability.All, Category.Eggs),
    MenuItem("Fried Egg Overhard", "FE OH", 20, Availability.All, Category.Eggs),
    MenuItem("Plain Omelet", "OM", 40, Availability.All, Category.Eggs),
    MenuItem("Veggie Omelet", "VEG OM", 60, Availability.All, Category.Eggs),
    MenuItem("Deluxe Omelet", "DXL OM", 115, Availability.All, Category.Eggs),
    MenuItem("Cheese Omelet", "OM CH", 60, Availability.All, Category.Eggs),
    MenuItem("Fresh Tomato Omelet", "OM FRT", 45, Availability.All, Category.Eggs),
    MenuItem("Pesto Omelet", "PSTO OM", 70, Availability.All, Category.Eggs),
    MenuItem("Olive Omelet", "OLV OM", 75, Availability.All, Category.Eggs),
    MenuItem("Veggie Cheese Omelet", "VEG CH OM", 80, Availability.All, Category.Eggs),
    MenuItem("Gourmet Omelet", "GM OM", 110, Availability.All, Category.Eggs),
    MenuItem("Onion Omelet", "ON OM", 45, Availability.All, Category.Eggs)
)