package edu.amrita.amritacafe.menu

val menuString = listOf(
    MenuItem("Granola", "Gran", 3f, Availability.All, Category.Breakfast),
    MenuItem("Chia", "Chia", 3f, Availability.All, Category.Breakfast),
    MenuItem("Bagels", "Bag", 3f, Availability.All, Category.Breakfast),
    MenuItem("chream cheese", "cheese", 1f, Availability.All, Category.Breakfast),
    MenuItem("Breakfast Sandwich", "Br Sand", 4f, Availability.All, Category.Breakfast),

    MenuItem("Samosa", "Sam", 15f, Availability.All, Category.Indian_Snacks),
    MenuItem("Eggplant Bhaji", "Eg Bhaj", 15f, Availability.All, Category.Indian_Snacks),
    MenuItem("Aloo Tikki", "Tikki", 15f, Availability.All, Category.Indian_Snacks),
    MenuItem("Bonda", "Bonda", 1.5f, Availability.All, Category.Indian_Snacks),
    MenuItem("Parippu Vada", "Parip", 1.5f, Availability.All, Category.Indian_Snacks),
    MenuItem("Methu Vada", "Methu", 1.5f, Availability.All, Category.Indian_Snacks),
    MenuItem("Cauliflower", "Ca Bhaj", 1.5f, Availability.All, Category.Indian_Snacks),
    MenuItem("Idli", "Idli", 1.25f, Availability.All, Category.Curry_Corner),
    MenuItem("Sambar", "Sam", 2f, Availability.All, Category.Curry_Corner),
    MenuItem("Puri", "Puri", 1.5f, Availability.All, Category.Curry_Corner),
    MenuItem("Chole", "Chole", 2f, Availability.All, Category.Curry_Corner),
    MenuItem("Panner Curry", "Pa Curry", 3.5f, Availability.All, Category.Curry_Corner),
    MenuItem("Appam Curry", "Ap Curry", 3.5f, Availability.All, Category.Curry_Corner),
    MenuItem("Appam", "Appam", 2f, Availability.All, Category.Curry_Corner),

    MenuItem("Masala Dosa", "Ma Dosa", 7f, Availability.All, Category.Dosa_and_More),
    MenuItem("Plain Dosa", "Dosa", 6f, Availability.All, Category.Dosa_and_More),
    MenuItem("Quiona Upma", "Upuma", 2f, Availability.All, Category.Dosa_and_More),
    MenuItem("Poha", "Poha", 2f, Availability.All, Category.Dosa_and_More),
    MenuItem("Bhel puri", "Bel Pu", 7f, Availability.All, Category.Dosa_and_More),
    MenuItem("Dahi Chaat", "Dah Cha", 7f, Availability.All, Category.Dosa_and_More),
    MenuItem("Papdi Chaat", "Pap Cha", 7f, Availability.All, Category.Dosa_and_More),
    MenuItem("Sev Puri", "Sev Pu", 7f, Availability.All, Category.Dosa_and_More),
    MenuItem("Dahi Puri", "Dah Pu", 7f, Availability.All, Category.Dosa_and_More),
    MenuItem("Uttapam", "Uttap", 5f, Availability.All, Category.Dosa_and_More),
    MenuItem("Bhutura", "", 5f, Availability.All, Category.Dosa_and_More),

    MenuItem("Cheese Pizza", "Ch Piz", 3f, Availability.All, Category.Pizza_and_More),
    MenuItem("Vegetarian Pizza", "Veg Piz", 3.5f, Availability.All, Category.Pizza_and_More),
    MenuItem("Panini regular", "Pan", 6f, Availability.All, Category.Pizza_and_More),
    MenuItem("Panini pesto", "Pan pes", 6f, Availability.All, Category.Pizza_and_More),
    MenuItem("Bom Panini", "Bom Pan", 6f, Availability.All, Category.Pizza_and_More),
    MenuItem("Veggie Puff", "Puff", 3f, Availability.All, Category.Pizza_and_More),
    MenuItem("Fries", "Fries", 3f, Availability.All, Category.Pizza_and_More),

    MenuItem("Raw Pie", "Raw Pi", 7f, Availability.All, Category.Raw),
    MenuItem("Raw Bar", "Raw Bar", 5f, Availability.All, Category.Raw),
    MenuItem("Springroll", "Spring", 5f, Availability.All, Category.Raw),
    MenuItem("Large cake", "lg Cake", 4f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Cake", "cake", 3.5f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Bars", "Bars", 3f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Cookies", "Cookie", 2f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Energy Balls", " E balls", 1f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Pie", "Pie", 4f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Whipped cream", "Cream", 3.5f, Availability.All, Category.Sweets_Homemade),
    MenuItem("Breakfast scones", "Scones", 3.5f, Availability.All, Category.Sweets_Homemade),

    MenuItem("Chai", "Chai", 2.5f, Availability.All, Category.Hot_Drinks),
    MenuItem("Veg Chai", "Chai", 3.5f, Availability.All, Category.Hot_Drinks),
    MenuItem("Espresso", "Esp", 2f, Availability.All, Category.Hot_Drinks),
    MenuItem("Americano", "Amer", 3f, Availability.All, Category.Hot_Drinks),
    MenuItem("Cappuchino", "Cap", 3.5f, Availability.All, Category.Hot_Drinks),
    MenuItem("Latte", "Lat", 5f, Availability.All, Category.Hot_Drinks),
    MenuItem("Madras Coffe", "Ma Cof", 3.5f, Availability.All, Category.Hot_Drinks),
    MenuItem("Filter Coffee", "Reg Cof", 3f, Availability.All, Category.Hot_Drinks),
    MenuItem("Herbal Tea", " Herb T", 2.5f, Availability.All, Category.Hot_Drinks),
    MenuItem("Mocha", "Moch", 5f, Availability.All, Category.Hot_Drinks),

    MenuItem("Lassi", "Lassi", 2.5f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("Orange Juice", "O Jui", 4f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("green Juice", "G Jui", 5f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("Red juice", "R Jui", 5f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("Yellow smoothie", "Y Smo", 6f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("Red smoothis", "R Smo", 6f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("Green smoothis", "Gr Smo", 6f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("Tumeric shot", "Tu shot", 3f, Availability.All, Category.Juice_and_Smoothie),
    MenuItem("wheet grass shot", "Wh shot", 4f, Availability.All, Category.Juice_and_Smoothie),

    MenuItem("All juice", "Col Dri", 2.5f, Availability.All, Category.Cold_Drinks),
    MenuItem("Yerba Mate", "Mate", 4.5f, Availability.All, Category.Cold_Drinks),
    MenuItem("Juice Box", "J Box", 1f, Availability.All, Category.Cold_Drinks),

    MenuItem("Chips", "Chips", 1f, Availability.All, Category.Cash_Register_Shelf),
    MenuItem("Chocolate", "Choco", 2f, Availability.All, Category.Cash_Register_Shelf)
)


val defaultMenu: List<MenuItem> = listOf(
    MenuItem("Bread", "BREAD", 3f, Availability.All, Category.Side),
    MenuItem("Butter", "BUTT", 10f, Availability.All, Category.Side),
    MenuItem("Capsicum", "CAP", 10f, Availability.All, Category.Side),
    MenuItem("Carrot", "CARROT", 10f, Availability.All, Category.Side),
    MenuItem("Honey", "HON", 10f, Availability.All, Category.Side),
    MenuItem("Jam", "JAM", 10f, Availability.All, Category.Side),
    MenuItem("Sliced Cheese", "SL CH", 20f, Availability.All, Category.Side),
    MenuItem("Mustard", "MRD", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Choco Spread", "CHOC", 15f, Availability.All, Category.Side),
    MenuItem("Peanut Butter", "PB", 10f, Availability.All, Category.Side),
    MenuItem("Patty", "PATTY", 20f, Availability.LunchDinner, Category.Side),
    MenuItem("Cucumber", "CUKE", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Pesto", "PSTO", 25f, Availability.All, Category.Side),
    MenuItem("Raw Egg", "RAW EGG", 10f, Availability.All, Category.Side),
    MenuItem("Gomasio", "GOMAZ", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Ketchup", "KETUP", 5f, Availability.All, Category.Side),
    MenuItem("Olive", "OLV", 30f, Availability.All, Category.Side),
    MenuItem("Onion", "ON", 5f, Availability.All, Category.Side),
    MenuItem("Pickle", "PKL", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Dressing", "DRS", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Soya", "SOYA", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Sprouts", "SPRTS", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Fresh Tomato", "FRT", 5f, Availability.All, Category.Side),
    MenuItem("Tomato Sauce", "TOM", 10f, Availability.All, Category.Side),
    MenuItem("Bun", "BUN", 10f, Availability.LunchDinner, Category.Side),
    MenuItem("Grated Cheese", "CH", 20f, Availability.All, Category.Side),
    MenuItem("Mayo", "MAYO", 10f, Availability.LunchDinner, Category.Side),

    MenuItem("Sm Fries", "SMFF", 30f, Availability.LunchDinner, Category.Fries),
    MenuItem("Lg Fries", "LGFF", 60f, Availability.LunchDinner, Category.Fries),
    MenuItem("Sm Fries Salt", "SMSAFF", 35f, Availability.LunchDinner, Category.Fries),
    MenuItem("Lg Fries Salt", "LGSAFF", 70f, Availability.LunchDinner, Category.Fries),

    MenuItem("Grilled Cheese", "GC", 40f, Availability.All, Category.Sandwich),
    MenuItem("Egg Cheese Sand", "ECS", 60f, Availability.All, Category.Sandwich),
    MenuItem("Omelet Sandwich", "OMS", 50f, Availability.All, Category.Sandwich),
    MenuItem("Deluxe Grill CH", "DXL GC", 75f, Availability.LunchDinner, Category.Sandwich),
    MenuItem("Grilled Ch FRT", "GC FRT", 45f, Availability.LunchDinner, Category.Sandwich),

    MenuItem("Simple Salad", "SAL", 30f, Availability.LunchDinner, Category.Salad),
    MenuItem("Sprout Salad", "SPRSAL", 50f, Availability.LunchDinner, Category.Salad),
    MenuItem("Deluxe Salad", "DXL SAL", 90f, Availability.LunchDinner, Category.Salad),
    MenuItem("Pesto Salad", "PSTO SAL", 80f, Availability.LunchDinner, Category.Salad),
    MenuItem("Quinoa Salad", "QNA SAL", 150f, Availability.LunchDinner, Category.Salad),

    MenuItem("French Toast", "FT", 40f, Availability.Breakfast, Category.Breakfast),
    MenuItem("Ragi Pancake", "RAG PAN", 40f, Availability.Breakfast, Category.Breakfast),
    MenuItem("Pancake", "PAN", 40f, Availability.Breakfast, Category.Breakfast),
    MenuItem("Hash Brown", "HASH", 20f, Availability.Breakfast, Category.Breakfast),
    MenuItem("Oatmeal", "OAT", 30f, Availability.Breakfast, Category.Breakfast),
    MenuItem("Ragi Porridge", "POR", 30f, Availability.Breakfast, Category.Breakfast),
    MenuItem("Vegan Omelet", "VN OM", 40f, Availability.Breakfast, Category.Breakfast),

    MenuItem("Cheese Pizza", "CH PZA", 100f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Olive Pizza", "OLV PZA", 135f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Veg Pizza", "VEG PZA", 125f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Vegan Veg Pizza", "VN VEG PZA", 100f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Gourmet Pizza", "GM PZA", 150f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Vegan Gourmet PZA", "VN GM PZA", 125f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Pesto Pizza", "PSTO PZA", 125f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Paneer Pizza", "PAN PZA", 150f, Availability.LunchDinner, Category.Pizza),
    MenuItem("Mediter. Pizza", "MED PZA", 125f, Availability.LunchDinner, Category.Pizza),

    MenuItem("Veggie Burger", "VB", 40f, Availability.LunchDinner, Category.Burger),
    MenuItem("Cheese Burger", "CB", 60f, Availability.LunchDinner, Category.Burger),
    MenuItem("Patty", "PATTY", 20f, Availability.LunchDinner, Category.Burger),
    MenuItem("Deluxe Burger", "DLXB", 80f, Availability.LunchDinner, Category.Burger),
    MenuItem("Pesto Burger", "PSTOB", 65f, Availability.LunchDinner, Category.Burger),

    MenuItem("Toast", "T", 3f, Availability.All, Category.Toast),
    MenuItem("Butter Jam Toast", "BJT", 15f, Availability.All, Category.Toast),
    MenuItem("Butter Toast", "BT", 10f, Availability.All, Category.Toast),
    MenuItem("Jam Toast", "JT", 10f, Availability.All, Category.Toast),
    MenuItem("Peanut But Toast", "PBT", 10f, Availability.All, Category.Toast),
    MenuItem("Cheese Toast", "CHT", 25f, Availability.All, Category.Toast),
    MenuItem("Honey Toast", "HT", 10f, Availability.All, Category.Toast),
    MenuItem("Butter Honey Toast", "BHT", 20f, Availability.All, Category.Toast),
    MenuItem("Choco Toast", "CHOC T", 15f, Availability.All, Category.Toast),

    MenuItem("Kitcheri", "KITCH", 30f, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Steamed Veg", "ST VEG", 30f, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Quinoa", "QNA", 100f, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Steamed Broccoli", "ST BROC", 100f, Availability.LunchDinner, Category.Kitcheri),
    MenuItem("Hummus", "HUM", 30f, Availability.LunchDinner, Category.Kitcheri),

    MenuItem("Jam", "JAM", 10f, Availability.Breakfast, Category.Topping),
    MenuItem("Peanut Butter", "PB", 10f, Availability.Breakfast, Category.Topping),
    MenuItem("Butter", "BUTT", 10f, Availability.Breakfast, Category.Topping),
    MenuItem("Honey", "HON", 10f, Availability.Breakfast, Category.Topping),
    MenuItem("Choco Spread", "CHOC", 15f, Availability.Breakfast, Category.Topping),

    MenuItem("Plain Pasta", "PL PSTA", 30f, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pasta Tomato Sauce", "PSTA TOM", 60f, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pasta Tomato Cheese", "PAST TOM CH", 80f, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pasta All Soy", "PAST ALL SOY", 90f, Availability.LunchDinner, Category.Pasta),
    MenuItem("Pesto Pasta", "PSTO PAST", 60f, Availability.LunchDinner, Category.Pasta),
    MenuItem("Vegan Gourmet Pasta", "VN GM PAST", 100f, Availability.LunchDinner, Category.Pasta),
    MenuItem("Deluxe Pasta", "DLX PAST", 115f, Availability.LunchDinner, Category.Pasta),

    MenuItem("Egg Sunny Side Up", "FE SSU", 20f, Availability.All, Category.Eggs),
    MenuItem("Fried Egg Overhard", "FE OH", 20f, Availability.All, Category.Eggs),
    MenuItem("Plain Omelet", "OM", 40f, Availability.All, Category.Eggs),
    MenuItem("Veggie Omelet", "VEG OM", 60f, Availability.All, Category.Eggs),
    MenuItem("Deluxe Omelet", "DXL OM", 115f, Availability.All, Category.Eggs),
    MenuItem("Cheese Omelet", "OM CH", 60f, Availability.All, Category.Eggs),
    MenuItem("Fresh Tomato Omelet", "OM FRT", 45f, Availability.All, Category.Eggs),
    MenuItem("Pesto Omelet", "PSTO OM", 70f, Availability.All, Category.Eggs),
    MenuItem("Olive Omelet", "OLV OM", 75f, Availability.All, Category.Eggs),
    MenuItem("Veggie Cheese Omelet", "VEG CH OM", 80f, Availability.All, Category.Eggs),
    MenuItem("Gourmet Omelet", "GM OM", 110f, Availability.All, Category.Eggs),
    MenuItem("Onion Omelet", "ON OM", 45f, Availability.All, Category.Eggs)
)